### Documentation du module de NLP et Tutoriel Jupyter : classification de films avec le pipeline NLP Naive Bayes / Regression logistique combiner avec le module d'optimisation et sélection de modèles

## Pipeline Complet: NLP + Classification Multilabel

**Étapes:**
1. **Prétraitement du texte (X)**: Tokenization → Suppression stopwords → TF-IDF
2. **Encodage des labels (y)**: Convertir chaque genre en colonne binaire (multilabel binarization)
3. **Entraînement**: Utiliser LogisticRegression avec OneVsRest (approche standard pour multilabel)
4. **Évaluation**: Metrics adaptées au multilabel (Hamming Loss, Precision, Recall, F1)

Dataset link : https://www.kaggle.com/datasets/kishoreramb/movies-dataset

In [1]:
import sys 
sys.path.append(r"E:\cours ifri\Programmation et BD\Python\Pdf et tpcours\Concepts et Application\Apprentissage Automatique\ifri_mini_ml_lib")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ifri_mini_ml_lib.preprocessing.preparation.encoding import OneHotEncoder
from ifri_mini_ml_lib.preprocessing.text.test_stopwords import StopWordRemover
from ifri_mini_ml_lib.preprocessing.preparation.tf_idf import TFIDFVectorizer 
from ifri_mini_ml_lib.preprocessing.preparation.tokenization import Tokenizer
from ifri_mini_ml_lib.preprocessing.preparation import DataSplitter
from ifri_mini_ml_lib.preprocessing.text.stop_word import StopWordRemover
from ifri_mini_ml_lib.preprocessing.preparation.tf_idf import TFIDFVectorizer


# Modeles de Classification
from ifri_mini_ml_lib.classification.logistic_regression import LogisticRegression

# Cross Validation 
from ifri_mini_ml_lib.model_selection.cross_validation import k_fold_cross_validation

In [3]:
df = pd.read_csv("movies.csv" , usecols=["genres" , "overview"])



df.dropna(inplace=True)

In [4]:
df.isna().sum()

genres      0
overview    0
dtype: int64

In [5]:
# Petite modification de formatage 
df['genres'] = df['genres'].str.replace(
    "Science Fiction",
    "Science_Fiction"
)

In [6]:
splitter = DataSplitter(seed=42)


X = df[["overview"]]
y = df["genres"]




X_train, X_test, y_train, y_test = splitter.train_test_split(X, y, test_size=0.2)

X_train, X_test, y_train, y_test = pd.DataFrame(X_train) , pd.DataFrame(X_test) , pd.DataFrame(y_train), pd.DataFrame(y_test)
# Proportions:
print(f"Train: {len(X_train)}, Test: {len(X_test)}")

Train: 3818, Test: 954

In [7]:
# Pipeline NLP simple: Tokenization → Stopwords → TF-IDF

# 1. Tokenizer
tokenizer = Tokenizer()

# 2. Stop words remover

stopwords_remover = StopWordRemover(language='english')

# 3. TF-IDF

tfidf = TFIDFVectorizer()

# Utilisation:
# X_train_tokens = [tokenizer.tokenize(text) for text in X_train]  # Tokenize chaque texte
# X_train_cleaned = [stopwords_remover.transform(tokens) for tokens in X_train_tokens]  # Remove stopwords
# X_train_tfidf = tfidf.fit_transform(X_train_cleaned)  # TF-IDF

In [8]:
X.describe()

                                                 overview
count                                                4772
unique                                               4772
top     In the 22nd century, a paraplegic Marine is di...
freq                                                    1

In [9]:
X_train_tokens = X_train['overview'].apply(tokenizer.tokenize)
X_train_tokens.head()

2922    [when, rachel, phelps, inherits, the, clevelan...
3699    [the, filmed, adaptation, from, david, benioff...
113     [returning, for, his, fifth, year, of, study, ...
4720    [nat, turner, a, former, slave, in, america, l...
1374    [three, detectives, in, the, corrupt, and, bru...
Name: overview, dtype: object

In [10]:
X_train_without_stop_words = X_train_tokens.apply(stopwords_remover.fit_transform)
X_train_without_stop_words.head()

2922    [rachel, phelps, inherits, cleveland, indians,...
3699    [filmed, adaptation, david, benioff, novel, na...
113     [returning, fifth, year, study, hogwarts, harr...
4720    [nat, turner, former, slave, america, leads, l...
1374    [three, detectives, corrupt, brutal, l, police...
Name: overview, dtype: object

In [11]:
X_train_encoded = pd.DataFrame(tfidf.fit_transform(X_train_without_stop_words.tolist()))
X_train_encoded.head()

,0,1,2,3,4,5,6,7,8,9,...,18847,18848,18849,18850,18851,18852,18853,18854,18855,18856
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
y[0]

'Action Adventure Fantasy Science_Fiction'

In [13]:
# Observez la structure des genres
print("=== OBSERVATION DES GENRES ===\n")

# Exemples de genres bruts
print("Exemples de genres (premiers 10):")
print(y.head(10))

print(f"\nNombre total de films: {len(y)}")
print(f"Type de données: {type(y.iloc[0])}")

# Tous les genres uniques
all_genres_str = ' '.join(y.values)
unique_genres = set(all_genres_str.split())
print(f"\nGenres uniques totaux: {sorted(unique_genres)}")
print(f"Nombre de genres uniques: {len(unique_genres)}")

# Nombre de genres par film
y_genre_count = y.str.split().apply(len)
print(f"\nNombre de genres par film:")
print(y_genre_count.value_counts().sort_index())

=== OBSERVATION DES GENRES ===

Exemples de genres (premiers 10):
0    Action Adventure Fantasy Science_Fiction
1                    Adventure Fantasy Action
2                      Action Adventure Crime
3                 Action Crime Drama Thriller
4            Action Adventure Science_Fiction
5                    Fantasy Action Adventure
6                            Animation Family
7            Action Adventure Science_Fiction
8                    Adventure Fantasy Family
9                    Action Adventure Fantasy
Name: genres, dtype: object

Nombre total de films: 4772
Type de données: <class 'str'>

Genres uniques totaux: ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Movie', 'Music', 'Mystery', 'Romance', 'Science_Fiction', 'TV', 'Thriller', 'War', 'Western']
Nombre de genres uniques: 21

Nombre de genres par film:
genres
1     897
2    1489
3    1524
4     634
5     227
6       1
Name: count, dtype: int64

In [14]:
# Faire le prétraitement du test de la meme facon que le train


# Tokenizer -> StopWords -> TFIDFVectorizer


X_test_tokens = X_test['overview'].apply(tokenizer.tokenize)

X_test_without_stop_words = X_test_tokens.apply(stopwords_remover.transform)

X_test_encoded = pd.DataFrame(tfidf.transform(X_test_without_stop_words.tolist()))

print(f"X_test shape: {X_test_encoded.shape}")
print(f"X_test: {len(X_test_encoded)}")

X_test shape: (954, 18857)
X_test: 954

In [15]:
# ÉTAPE 2: Encodage Multilabel des genres (y_train, y_test) 
label_to_idx = {
    label: idx
    for idx, label in enumerate(unique_genres)
}
y_train_multilabel = np.zeros(
    (y_train.shape[0] , len(unique_genres)),
    dtype=np.int8
)

for idx , line in enumerate(y_train.values):
    print(f"IDX = {idx} , line = {line}")
    for genre in line[0].split():

        j = label_to_idx[genre]

        y_train_multilabel[idx, j] = 1
        
y_train_multilabel[:10]

IDX = 0 , line = ['Comedy']
IDX = 1 , line = ['Crime Drama']
IDX = 2 , line = ['Adventure Fantasy Family Mystery']
IDX = 3 , line = ['Drama']
IDX = 4 , line = ['Crime Drama Mystery Thriller']
IDX = 5 , line = ['Adventure Animation Family Fantasy']
IDX = 6 , line = ['Crime Drama Horror Thriller']
IDX = 7 , line = ['Documentary']
IDX = 8 , line = ['Drama']
IDX = 9 , line = ['Comedy Music Romance']
IDX = 10 , line = ['Fantasy Drama Comedy Family']
IDX = 11 , line = ['Drama']
IDX = 12 , line = ['Horror Thriller']
IDX = 13 , line = ['Drama History']
IDX = 14 , line = ['Action Adventure Science_Fiction Thriller']
IDX = 15 , line = ['Drama']
IDX = 16 , line = ['Action Fantasy Horror']
IDX = 17 , line = ['Action Drama Thriller']
IDX = 18 , line = ['Drama Romance']
IDX = 19 , line = ['Animation Music Family']
IDX = 20 , line = ['Science_Fiction Drama']
IDX = 21 , line = ['Drama']
IDX = 22 , line = ['Comedy Adventure Romance']
IDX = 23 , line = ['Romance Drama Comedy Music']
IDX = 24 , line = ['Documentary Family']
IDX = 25 , line = ['Comedy Romance']
IDX = 26 , line = ['Documentary']
IDX = 27 , line = ['Comedy']
IDX = 28 , line = ['Romance Comedy Drama']
IDX = 29 , line = ['Thriller']
IDX = 30 , line = ['Crime Drama']
IDX = 31 , line = ['Drama Horror Thriller']
IDX = 32 , line = ['History Action Drama']
IDX = 33 , line = ['Horror Mystery Thriller']
IDX = 34 , line = ['Drama Comedy Horror']
IDX = 35 , line = ['Action Comedy Drama']
IDX = 36 , line = ['Romance Drama']
IDX = 37 , line = ['Action Comedy Drama History']
IDX = 38 , line = ['Documentary']
IDX = 39 , line = ['Comedy Romance']
IDX = 40 , line = ['Drama Mystery']
IDX = 41 , line = ['Comedy Family Science_Fiction']
IDX = 42 , line = ['Drama Romance']
IDX = 43 , line = ['Comedy Crime']
IDX = 44 , line = ['Horror Mystery']
IDX = 45 , line = ['Comedy Crime Drama']
IDX = 46 , line = ['Drama Comedy']
IDX = 47 , line = ['Action Adventure Thriller']
IDX = 48 , line = ['Drama Thriller']
IDX = 49 , line = ['Action Drama Thriller']
IDX = 50 , line = ['Romance Comedy']
IDX = 51 , line = ['Comedy Drama']
IDX = 52 , line = ['Drama']
IDX = 53 , line = ['Drama']
IDX = 54 , line = ['Drama']
IDX = 55 , line = ['Crime Thriller']
IDX = 56 , line = ['Drama Comedy Music']
IDX = 57 , line = ['Drama Crime']
IDX = 58 , line = ['Animation Family Adventure Comedy Fantasy']
IDX = 59 , line = ['Fantasy Horror Action']
IDX = 60 , line = ['Comedy']
IDX = 61 , line = ['Adventure Action Science_Fiction']
IDX = 62 , line = ['Music']
IDX = 63 , line = ['Comedy Romance']
IDX = 64 , line = ['Romance Comedy Music']
IDX = 65 , line = ['Fantasy Comedy Family']
IDX = 66 , line = ['Thriller']
IDX = 67 , line = ['Drama']
IDX = 68 , line = ['Action Science_Fiction Thriller']
IDX = 69 , line = ['Family Action Adventure']
IDX = 70 , line = ['Drama']
IDX = 71 , line = ['Documentary']
IDX = 72 , line = ['Drama Comedy Romance']
IDX = 73 , line = ['Horror Thriller']
IDX = 74 , line = ['Drama']
IDX = 75 , line = ['Family Animation Drama']
IDX = 76 , line = ['Drama']
IDX = 77 , line = ['Comedy']
IDX = 78 , line = ['Action Science_Fiction']
IDX = 79 , line = ['Mystery Horror']
IDX = 80 , line = ['Fantasy Comedy Drama']
IDX = 81 , line = ['Romance Drama']
IDX = 82 , line = ['Comedy Drama']
IDX = 83 , line = ['Drama']
IDX = 84 , line = ['Adventure Fantasy Action Comedy Science_Fiction']
IDX = 85 , line = ['Thriller Horror Science_Fiction']
IDX = 86 , line = ['Comedy Drama']
IDX = 87 , line = ['Drama Horror']
IDX = 88 , line = ['Documentary']
IDX = 89 , line = ['Action Thriller']
IDX = 90 , line = ['Action Comedy Thriller']
IDX = 91 , line = ['Comedy Romance']
IDX = 92 , line = ['Action Drama Crime']
IDX = 93 , line = ['Comedy']
IDX = 94 , line = ['Drama']
IDX = 95 , line = ['Action Adventure Crime Mystery']
IDX = 96 , line = ['Drama Music Romance']
IDX = 97 , line = ['Drama']
IDX = 98 , line = ['Comedy']
IDX = 99 , line = ['Action Drama Thriller']
IDX = 100 , line = ['Drama']
IDX = 101 , line = ['Drama Music Romance']
IDX = 102 , line = ['Fantasy Horror Thriller']
IDX = 103 , line = ['Drama Science_Fiction']
IDX = 104 , line = ['Adventure Fantasy Action Thriller']
IDX = 105 , line = ['Comedy Fantasy']
IDX = 106 , line = ['Comedy Drama']
IDX = 107 , line = ['Comedy Drama']
IDX = 108 , line = ['Drama']
IDX = 109 , line = ['Drama Horror Thriller']
IDX = 110 , line = ['Comedy Music Mystery Crime']
IDX = 111 , line = ['Crime Drama Horror Thriller']
IDX = 112 , line = ['Mystery Science_Fiction Thriller']
IDX = 113 , line = ['Action Adventure Fantasy Horror Science_Fiction']
IDX = 114 , line = ['Romance Comedy']
IDX = 115 , line = ['Music Horror']
IDX = 116 , line = ['Animation Comedy Drama Family Fantasy']
IDX = 117 , line = ['Science_Fiction Comedy Adventure']
IDX = 118 , line = ['Family Fantasy']
IDX = 119 , line = ['Action Adventure Fantasy Science_Fiction']
IDX = 120 , line = ['Action Thriller']
IDX = 121 , line = ['Action Drama']
IDX = 122 , line = ['Horror Comedy']
IDX = 123 , line = ['Documentary']
IDX = 124 , line = ['Drama Thriller History War']
IDX = 125 , line = ['Drama']
IDX = 126 , line = ['Crime Drama Thriller Action']
IDX = 127 , line = ['Drama Romance']
IDX = 128 , line = ['Action']
IDX = 129 , line = ['Comedy Drama Romance']
IDX = 130 , line = ['Action Western']
IDX = 131 , line = ['Drama Foreign Romance']
IDX = 132 , line = ['Drama Family']
IDX = 133 , line = ['Drama Music Romance']
IDX = 134 , line = ['Thriller Science_Fiction Adventure Action']
IDX = 135 , line = ['Drama Romance']
IDX = 136 , line = ['Action Adventure Drama Thriller']
IDX = 137 , line = ['Drama Music']
IDX = 138 , line = ['Drama Romance']
IDX = 139 , line = ['Comedy Drama']
IDX = 140 , line = ['Animation Comedy Family']
IDX = 141 , line = ['Thriller Science_Fiction Mystery']
IDX = 142 , line = ['Drama Thriller']
IDX = 143 , line = ['Comedy']
IDX = 144 , line = ['Science_Fiction Thriller']
IDX = 145 , line = ['Horror Comedy Science_Fiction']
IDX = 146 , line = ['Comedy']
IDX = 147 , line = ['Action Comedy Crime Thriller']
IDX = 148 , line = ['Crime Drama Thriller']
IDX = 149 , line = ['Action Comedy Documentary']
IDX = 150 , line = ['Thriller Drama Mystery']
IDX = 151 , line = ['Comedy']
IDX = 152 , line = ['Comedy Romance']
IDX = 153 , line = ['Drama']
IDX = 154 , line = ['Drama Thriller']
IDX = 155 , line = ['Drama Mystery']
IDX = 156 , line = ['Drama Thriller Crime Mystery']
IDX = 157 , line = ['Drama Action War History']
IDX = 158 , line = ['Action Adventure Horror Thriller']
IDX = 159 , line = ['Comedy']
IDX = 160 , line = ['Comedy Crime']
IDX = 161 , line = ['Action Adventure Thriller']
IDX = 162 , line = ['Comedy Drama Romance']
IDX = 163 , line = ['Adventure Comedy Family Science_Fiction']
IDX = 164 , line = ['Documentary Music']
IDX = 165 , line = ['Drama']
IDX = 166 , line = ['Science_Fiction Comedy Drama Crime']
IDX = 167 , line = ['Drama Romance']
IDX = 168 , line = ['Adventure Fantasy Action']
IDX = 169 , line = ['Horror']
IDX = 170 , line = ['Crime Thriller']
IDX = 171 , line = ['Action Thriller Adventure']
IDX = 172 , line = ['Action Drama Thriller']
IDX = 173 , line = ['Action Thriller']
IDX = 174 , line = ['Horror']
IDX = 175 , line = ['Comedy Romance']
IDX = 176 , line = ['Action Drama']
IDX = 177 , line = ['Drama']
IDX = 178 , line = ['Horror Thriller']
IDX = 179 , line = ['Science_Fiction Action Adventure Thriller']
IDX = 180 , line = ['Action Adventure Comedy Family']
IDX = 181 , line = ['Crime Mystery Thriller']
IDX = 182 , line = ['Family Fantasy Adventure']
IDX = 183 , line = ['Drama Comedy Music']
IDX = 184 , line = ['Adventure Animation Comedy Family Fantasy']
IDX = 185 , line = ['Comedy Drama']
IDX = 186 , line = ['Foreign Documentary']
IDX = 187 , line = ['Crime Action Thriller']
IDX = 188 , line = ['Comedy']
IDX = 189 , line = ['Comedy Adventure']
IDX = 190 , line = ['Drama Foreign History']
IDX = 191 , line = ['Science_Fiction Adventure Action']
IDX = 192 , line = ['Comedy']
IDX = 193 , line = ['Adventure Action Thriller']
IDX = 194 , line = ['Action Thriller Drama']
IDX = 195 , line = ['Adventure Action Thriller']
IDX = 196 , line = ['Action Adventure Comedy Thriller']
IDX = 197 , line = ['Comedy']
IDX = 198 , line = ['Drama History']
IDX = 199 , line = ['Comedy']
IDX = 200 , line = ['Comedy']
IDX = 201 , line = ['Fantasy Comedy Science_Fiction Romance']
IDX = 202 , line = ['Comedy Romance TV Movie']
IDX = 203 , line = ['Horror Mystery']
IDX = 204 , line = ['Horror']
IDX = 205 , line = ['Thriller Action Drama History']
IDX = 206 , line = ['Drama Mystery Thriller']
IDX = 207 , line = ['Action Thriller Science_Fiction']
IDX = 208 , line = ['Thriller Crime Drama']
IDX = 209 , line = ['Drama Thriller Science_Fiction Mystery']
IDX = 210 , line = ['Romance Drama']
IDX = 211 , line = ['Drama Thriller Mystery']
IDX = 212 , line = ['Comedy Crime']
IDX = 213 , line = ['Drama Mystery Thriller']
IDX = 214 , line = ['Thriller Comedy Horror']
IDX = 215 , line = ['Comedy Drama Romance']
IDX = 216 , line = ['Comedy Documentary']
IDX = 217 , line = ['Music Drama']
IDX = 218 , line = ['Comedy']
IDX = 219 , line = ['Documentary']
IDX = 220 , line = ['Adventure Drama Family']
IDX = 221 , line = ['Drama']
IDX = 222 , line = ['Animation Comedy Adventure Family']
IDX = 223 , line = ['Drama Thriller Crime']
IDX = 224 , line = ['Documentary Music Family']
IDX = 225 , line = ['Drama']
IDX = 226 , line = ['Action Crime Drama Thriller']
IDX = 227 , line = ['Drama Comedy Family']
IDX = 228 , line = ['Drama Thriller']
IDX = 229 , line = ['Comedy']
IDX = 230 , line = ['Comedy Drama Family Music']
IDX = 231 , line = ['Animation Family']
IDX = 232 , line = ['Comedy Drama']
IDX = 233 , line = ['Comedy Family']
IDX = 234 , line = ['Crime Mystery Thriller']
IDX = 235 , line = ['Comedy Romance']
IDX = 236 , line = ['Comedy Drama Romance']
IDX = 237 , line = ['Comedy Drama Family Science_Fiction']
IDX = 238 , line = ['Horror']
IDX = 239 , line = ['Horror Thriller']
IDX = 240 , line = ['Drama']
IDX = 241 , line = ['Comedy Romance']
IDX = 242 , line = ['Drama']
IDX = 243 , line = ['Comedy Drama']
IDX = 244 , line = ['Comedy']
IDX = 245 , line = ['Comedy Romance Crime Drama Mystery']
IDX = 246 , line = ['Drama Crime Thriller']
IDX = 247 , line = ['Action Crime Thriller Drama']
IDX = 248 , line = ['Comedy Drama Romance']
IDX = 249 , line = ['Adventure Comedy Drama']
IDX = 250 , line = ['Comedy']
IDX = 251 , line = ['Drama']
IDX = 252 , line = ['Comedy Drama']
IDX = 253 , line = ['Crime Drama Horror Thriller']
IDX = 254 , line = ['Comedy']
IDX = 255 , line = ['Comedy Drama Family Music']
IDX = 256 , line = ['Crime Drama']
IDX = 257 , line = ['Comedy Romance']
IDX = 258 , line = ['Drama Family Comedy']
IDX = 259 , line = ['Science_Fiction Action Adventure']
IDX = 260 , line = ['Science_Fiction Drama']
IDX = 261 , line = ['Comedy']
IDX = 262 , line = ['Drama Music']
IDX = 263 , line = ['Thriller Horror']
IDX = 264 , line = ['Thriller Action Fantasy Horror']
IDX = 265 , line = ['Drama Romance']
IDX = 266 , line = ['Drama Comedy Foreign']
IDX = 267 , line = ['Fantasy Drama Crime']
IDX = 268 , line = ['Drama Thriller']
IDX = 269 , line = ['Drama Comedy']
IDX = 270 , line = ['Comedy']
IDX = 271 , line = ['Action Adventure Thriller War']
IDX = 272 , line = ['Action Adventure Animation Science_Fiction Thriller']
IDX = 273 , line = ['Drama Crime Thriller']
IDX = 274 , line = ['Fantasy Drama War']
IDX = 275 , line = ['Action Crime Thriller']
IDX = 276 , line = ['Thriller Horror']
IDX = 277 , line = ['Science_Fiction Thriller']
IDX = 278 , line = ['Drama Thriller Fantasy Mystery']
IDX = 279 , line = ['Comedy Drama']
IDX = 280 , line = ['Drama']
IDX = 281 , line = ['Comedy Romance']
IDX = 282 , line = ['Action Adventure Comedy']
IDX = 283 , line = ['Comedy']
IDX = 284 , line = ['Comedy Crime']
IDX = 285 , line = ['Music Documentary']
IDX = 286 , line = ['Comedy Romance']
IDX = 287 , line = ['Thriller Mystery Science_Fiction']
IDX = 288 , line = ['Adventure Fantasy Action']
IDX = 289 , line = ['Family Fantasy']
IDX = 290 , line = ['Action Comedy Crime']
IDX = 291 , line = ['Romance Drama Comedy']
IDX = 292 , line = ['Comedy Science_Fiction']
IDX = 293 , line = ['Drama History Romance']
IDX = 294 , line = ['Drama Romance']
IDX = 295 , line = ['Action Comedy Thriller']
IDX = 296 , line = ['Action Comedy']
IDX = 297 , line = ['Drama Romance']
IDX = 298 , line = ['Crime Drama Romance Thriller']
IDX = 299 , line = ['Drama']
IDX = 300 , line = ['Comedy Adventure']
IDX = 301 , line = ['Comedy']
IDX = 302 , line = ['Comedy']
IDX = 303 , line = ['Drama']
IDX = 304 , line = ['Comedy']
IDX = 305 , line = ['Drama Thriller Science_Fiction']
IDX = 306 , line = ['Drama Mystery']
IDX = 307 , line = ['Drama Comedy']
IDX = 308 , line = ['Action Science_Fiction Adventure']
IDX = 309 , line = ['Comedy Documentary']
IDX = 310 , line = ['Mystery Adventure Crime']
IDX = 311 , line = ['Comedy Crime Romance']
IDX = 312 , line = ['Drama Romance Comedy']
IDX = 313 , line = ['Drama Thriller War']
IDX = 314 , line = ['Horror Action Thriller Crime']
IDX = 315 , line = ['Crime Mystery Thriller']
IDX = 316 , line = ['Action Comedy Thriller']
IDX = 317 , line = ['Drama']
IDX = 318 , line = ['Drama Foreign Romance']
IDX = 319 , line = ['Comedy']
IDX = 320 , line = ['Western']
IDX = 321 , line = ['Action Adventure Fantasy']
IDX = 322 , line = ['Comedy Family']
IDX = 323 , line = ['Drama Mystery Romance']
IDX = 324 , line = ['Drama Comedy Crime']
IDX = 325 , line = ['Comedy']
IDX = 326 , line = ['Romance Comedy']
IDX = 327 , line = ['Horror Romance']
IDX = 328 , line = ['Drama Romance']
IDX = 329 , line = ['Drama Romance']
IDX = 330 , line = ['Comedy Horror']
IDX = 331 , line = ['Horror Thriller']
IDX = 332 , line = ['Adventure Comedy Family Fantasy Science_Fiction']
IDX = 333 , line = ['Adventure Comedy Family']
IDX = 334 , line = ['Fantasy Horror Science_Fiction']
IDX = 335 , line = ['Comedy Fantasy']
IDX = 336 , line = ['Drama']
IDX = 337 , line = ['Drama']
IDX = 338 , line = ['Action Comedy']
IDX = 339 , line = ['Adventure Action Science_Fiction']
IDX = 340 , line = ['Drama Music Romance']
IDX = 341 , line = ['Drama']
IDX = 342 , line = ['Comedy']
IDX = 343 , line = ['Comedy Drama']
IDX = 344 , line = ['Drama Comedy Romance']
IDX = 345 , line = ['Action Adventure']
IDX = 346 , line = ['Comedy Drama Music']
IDX = 347 , line = ['Action Fantasy']
IDX = 348 , line = ['Horror Thriller']
IDX = 349 , line = ['Action Thriller Crime']
IDX = 350 , line = ['Thriller Horror']
IDX = 351 , line = ['Action']
IDX = 352 , line = ['Adventure Family Fantasy']
IDX = 353 , line = ['Science_Fiction Action Adventure Thriller']
IDX = 354 , line = ['Crime Comedy Adventure']
IDX = 355 , line = ['Fantasy Comedy Romance Science_Fiction']
IDX = 356 , line = ['Comedy']
IDX = 357 , line = ['Fantasy Action Adventure']
IDX = 358 , line = ['Drama Horror Mystery Thriller']
IDX = 359 , line = ['Action Comedy']
IDX = 360 , line = ['Drama']
IDX = 361 , line = ['Crime Drama']
IDX = 362 , line = ['Horror Action Science_Fiction']
IDX = 363 , line = ['Fantasy Horror Action Thriller Science_Fiction']
IDX = 364 , line = ['Adventure Science_Fiction']
IDX = 365 , line = ['Action Fantasy']
IDX = 366 , line = ['Adventure Fantasy Animation Family']
IDX = 367 , line = ['Crime Drama Mystery Thriller']
IDX = 368 , line = ['Horror Thriller Mystery']
IDX = 369 , line = ['Drama History Thriller']
IDX = 370 , line = ['Drama']
IDX = 371 , line = ['Comedy Romance Drama']
IDX = 372 , line = ['Comedy']
IDX = 373 , line = ['Drama Comedy']
IDX = 374 , line = ['Music Drama Comedy']
IDX = 375 , line = ['Horror Thriller']
IDX = 376 , line = ['Crime Mystery Thriller Action']
IDX = 377 , line = ['Crime Drama']
IDX = 378 , line = ['Horror Thriller']
IDX = 379 , line = ['Comedy Romance']
IDX = 380 , line = ['Science_Fiction']
IDX = 381 , line = ['Action Adventure Comedy']
IDX = 382 , line = ['Comedy Romance']
IDX = 383 , line = ['Horror Mystery']
IDX = 384 , line = ['Comedy Romance']
IDX = 385 , line = ['Action Adventure Science_Fiction']
IDX = 386 , line = ['Crime Comedy Romance']
IDX = 387 , line = ['Adventure Action Thriller']
IDX = 388 , line = ['Documentary']
IDX = 389 , line = ['Comedy Romance']
IDX = 390 , line = ['Documentary Music Family']
IDX = 391 , line = ['Comedy']
IDX = 392 , line = ['Romance History']
IDX = 393 , line = ['Drama Romance Comedy']
IDX = 394 , line = ['Comedy Romance']
IDX = 395 , line = ['Drama']
IDX = 396 , line = ['Documentary']
IDX = 397 , line = ['Comedy']
IDX = 398 , line = ['Thriller Drama Mystery']
IDX = 399 , line = ['Action Drama Mystery Thriller']
IDX = 400 , line = ['Drama Romance']
IDX = 401 , line = ['Adventure Action Science_Fiction']
IDX = 402 , line = ['Documentary']
IDX = 403 , line = ['Drama Crime Mystery']
IDX = 404 , line = ['Thriller Comedy Mystery']
IDX = 405 , line = ['Comedy Romance']
IDX = 406 , line = ['Comedy Horror Science_Fiction']
IDX = 407 , line = ['Action Thriller']
IDX = 408 , line = ['Horror']
IDX = 409 , line = ['Adventure Family Fantasy']
IDX = 410 , line = ['Horror Thriller']
IDX = 411 , line = ['Drama Action Romance']
IDX = 412 , line = ['Comedy']
IDX = 413 , line = ['Action']
IDX = 414 , line = ['Comedy']
IDX = 415 , line = ['Thriller Drama Horror']
IDX = 416 , line = ['Adventure Family']
IDX = 417 , line = ['Drama']
IDX = 418 , line = ['Action Thriller']
IDX = 419 , line = ['Horror']
IDX = 420 , line = ['Comedy Drama']
IDX = 421 , line = ['War History Drama']
IDX = 422 , line = ['Western Adventure']
IDX = 423 , line = ['Fantasy Drama Science_Fiction']
IDX = 424 , line = ['Horror Thriller Science_Fiction']
IDX = 425 , line = ['Comedy Drama War']
IDX = 426 , line = ['Drama']
IDX = 427 , line = ['Animation Family']
IDX = 428 , line = ['Comedy Romance']
IDX = 429 , line = ['Comedy']
IDX = 430 , line = ['Thriller Drama Mystery']
IDX = 431 , line = ['Comedy Drama']
IDX = 432 , line = ['Comedy Drama Thriller']
IDX = 433 , line = ['Science_Fiction Drama']
IDX = 434 , line = ['Music Comedy Drama']
IDX = 435 , line = ['Comedy']
IDX = 436 , line = ['Thriller Crime']
IDX = 437 , line = ['Crime Thriller Mystery']
IDX = 438 , line = ['Action Adventure Comedy Crime Romance']
IDX = 439 , line = ['Drama']
IDX = 440 , line = ['Comedy Drama Family Romance']
IDX = 441 , line = ['Fantasy Comedy Romance']
IDX = 442 , line = ['Comedy Romance Drama']
IDX = 443 , line = ['Comedy Drama War']
IDX = 444 , line = ['Comedy Romance']
IDX = 445 , line = ['Action Drama History War']
IDX = 446 , line = ['Drama Family Music']
IDX = 447 , line = ['Action Crime Drama Thriller']
IDX = 448 , line = ['Adventure Action Thriller']
IDX = 449 , line = ['Comedy']
IDX = 450 , line = ['Action Science_Fiction']
IDX = 451 , line = ['Horror Science_Fiction']
IDX = 452 , line = ['Action Crime']
IDX = 453 , line = ['Adventure Family Fantasy']
IDX = 454 , line = ['Drama Romance']
IDX = 455 , line = ['Animation Comedy Family']
IDX = 456 , line = ['Comedy']
IDX = 457 , line = ['Drama']
IDX = 458 , line = ['Drama']
IDX = 459 , line = ['Action Adventure Comedy']
IDX = 460 , line = ['Drama Thriller']
IDX = 461 , line = ['Drama Romance']
IDX = 462 , line = ['Drama']
IDX = 463 , line = ['Action Adventure Thriller']
IDX = 464 , line = ['Comedy']
IDX = 465 , line = ['Fantasy Adventure Action Comedy Drama']
IDX = 466 , line = ['Drama Thriller']
IDX = 467 , line = ['Drama Romance War']
IDX = 468 , line = ['Adventure Action Science_Fiction']
IDX = 469 , line = ['Horror Mystery']
IDX = 470 , line = ['Documentary']
IDX = 471 , line = ['Action Crime']
IDX = 472 , line = ['Drama']
IDX = 473 , line = ['Action Comedy Horror Mystery Science_Fiction']
IDX = 474 , line = ['Thriller Science_Fiction Mystery']
IDX = 475 , line = ['Adventure Fantasy Drama Comedy Music']
IDX = 476 , line = ['Horror Thriller']
IDX = 477 , line = ['Drama War']
IDX = 478 , line = ['Comedy Family']
IDX = 479 , line = ['Animation Family Adventure Science_Fiction']
IDX = 480 , line = ['Crime Drama Thriller']
IDX = 481 , line = ['Action Crime Fantasy']

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]],
      dtype=int8)

In [16]:
#Encodage de test selon la meme technique
y_test_multilabel = np.zeros(
    (y_test.shape[0] , len(unique_genres)),
    dtype=np.int8
)

for idx , line in enumerate(y_test.values):
    print(f"IDX = {idx} , line = {line}")
    for genre in line[0].split():

        j = label_to_idx[genre]

        y_test_multilabel[idx, j] = 1
        
y_test_multilabel[:10]

IDX = 0 , line = ['Action Adventure Thriller War']
IDX = 1 , line = ['Adventure Fantasy Action']
IDX = 2 , line = ['Fantasy Comedy Family']
IDX = 3 , line = ['Adventure Action Science_Fiction Thriller']
IDX = 4 , line = ['Family Animation Adventure Comedy']
IDX = 5 , line = ['Action Adventure Fantasy']
IDX = 6 , line = ['Drama']
IDX = 7 , line = ['Adventure Action Fantasy']
IDX = 8 , line = ['Comedy']
IDX = 9 , line = ['Drama Fantasy Comedy']
IDX = 10 , line = ['Comedy Drama']
IDX = 11 , line = ['Action Science_Fiction Adventure Comedy Family']
IDX = 12 , line = ['Action Crime Thriller']
IDX = 13 , line = ['Comedy Drama']
IDX = 14 , line = ['Music Drama']
IDX = 15 , line = ['Drama Comedy Romance']
IDX = 16 , line = ['Action Adventure Thriller']
IDX = 17 , line = ['Action Thriller Crime']
IDX = 18 , line = ['Horror Thriller']
IDX = 19 , line = ['Animation Adventure Family']
IDX = 20 , line = ['Action Fantasy Thriller']
IDX = 21 , line = ['Drama War']
IDX = 22 , line = ['Horror Drama Science_Fiction']
IDX = 23 , line = ['Horror Thriller Mystery']
IDX = 24 , line = ['Drama']
IDX = 25 , line = ['Drama Thriller Crime']
IDX = 26 , line = ['Science_Fiction Action Horror']
IDX = 27 , line = ['Comedy']
IDX = 28 , line = ['Thriller Crime Mystery Drama']
IDX = 29 , line = ['Horror']
IDX = 30 , line = ['Action Adventure Animation Comedy Family']
IDX = 31 , line = ['Action Adventure Thriller']
IDX = 32 , line = ['Comedy Crime']
IDX = 33 , line = ['Drama']
IDX = 34 , line = ['Comedy']
IDX = 35 , line = ['Action']
IDX = 36 , line = ['Mystery Horror Science_Fiction']
IDX = 37 , line = ['Comedy']
IDX = 38 , line = ['Animation Family']
IDX = 39 , line = ['Adventure Fantasy Family']
IDX = 40 , line = ['Adventure Fantasy']
IDX = 41 , line = ['Action Adventure Drama History Romance']
IDX = 42 , line = ['Thriller Crime Drama']
IDX = 43 , line = ['Animation Comedy Family']
IDX = 44 , line = ['Drama Romance']
IDX = 45 , line = ['Action Thriller Crime']
IDX = 46 , line = ['Action Adventure Drama Thriller']
IDX = 47 , line = ['Fantasy']
IDX = 48 , line = ['Romance Drama']
IDX = 49 , line = ['Horror Action Thriller Science_Fiction']
IDX = 50 , line = ['Action Thriller']
IDX = 51 , line = ['Horror Thriller']
IDX = 52 , line = ['Action Comedy Romance Science_Fiction Thriller']
IDX = 53 , line = ['Comedy Romance']
IDX = 54 , line = ['Adventure Drama Family']
IDX = 55 , line = ['Drama']
IDX = 56 , line = ['Comedy Fantasy Thriller']
IDX = 57 , line = ['Comedy Romance Foreign']
IDX = 58 , line = ['Horror Thriller']
IDX = 59 , line = ['Crime Drama Thriller']
IDX = 60 , line = ['Horror Science_Fiction Thriller']
IDX = 61 , line = ['Action Drama']
IDX = 62 , line = ['Western']
IDX = 63 , line = ['Science_Fiction']
IDX = 64 , line = ['Drama History War']
IDX = 65 , line = ['Comedy Drama Romance']
IDX = 66 , line = ['Adventure']
IDX = 67 , line = ['Drama Action Crime Thriller']
IDX = 68 , line = ['Drama Mystery Thriller Crime']
IDX = 69 , line = ['Crime Comedy Romance']
IDX = 70 , line = ['Drama Thriller']
IDX = 71 , line = ['Thriller Drama Crime']
IDX = 72 , line = ['Comedy Romance']
IDX = 73 , line = ['Comedy Family Fantasy']
IDX = 74 , line = ['Romance Comedy Family']
IDX = 75 , line = ['Action Comedy Drama Thriller']
IDX = 76 , line = ['Adventure']
IDX = 77 , line = ['Action Comedy']
IDX = 78 , line = ['Drama Family Foreign']
IDX = 79 , line = ['Comedy']
IDX = 80 , line = ['Comedy']
IDX = 81 , line = ['Action Comedy Fantasy Science_Fiction']
IDX = 82 , line = ['Action Adventure Comedy Thriller']
IDX = 83 , line = ['Comedy Drama Fantasy Romance Science_Fiction']
IDX = 84 , line = ['Drama Music Romance']
IDX = 85 , line = ['Drama History Romance War']
IDX = 86 , line = ['Action Crime Thriller']
IDX = 87 , line = ['Comedy Drama Romance']
IDX = 88 , line = ['Documentary']
IDX = 89 , line = ['Action Adventure Crime Thriller']
IDX = 90 , line = ['Horror']
IDX = 91 , line = ['Drama Romance']
IDX = 92 , line = ['Comedy Romance']
IDX = 93 , line = ['Drama Romance']
IDX = 94 , line = ['Drama']
IDX = 95 , line = ['Science_Fiction Adventure Fantasy']
IDX = 96 , line = ['Action Adventure Comedy Thriller Crime']
IDX = 97 , line = ['Science_Fiction Drama Mystery']
IDX = 98 , line = ['Crime Drama']
IDX = 99 , line = ['Horror Thriller']
IDX = 100 , line = ['Drama']
IDX = 101 , line = ['Comedy Romance']
IDX = 102 , line = ['Action Science_Fiction']
IDX = 103 , line = ['Thriller']
IDX = 104 , line = ['Crime Comedy Action']
IDX = 105 , line = ['Documentary Music']
IDX = 106 , line = ['Romance Comedy']
IDX = 107 , line = ['Crime Thriller Horror']
IDX = 108 , line = ['Drama Romance']
IDX = 109 , line = ['Comedy']
IDX = 110 , line = ['Fantasy Action Thriller Science_Fiction']
IDX = 111 , line = ['Documentary']
IDX = 112 , line = ['Mystery Adventure Comedy']
IDX = 113 , line = ['Drama Romance']
IDX = 114 , line = ['Drama']
IDX = 115 , line = ['Crime Horror Mystery']
IDX = 116 , line = ['Comedy Documentary']
IDX = 117 , line = ['Comedy Drama']
IDX = 118 , line = ['Comedy Crime']
IDX = 119 , line = ['Action Crime Thriller']
IDX = 120 , line = ['Action Adventure Drama']
IDX = 121 , line = ['Family Comedy Drama']
IDX = 122 , line = ['Adventure Drama Action']
IDX = 123 , line = ['Action Adventure Drama History War']
IDX = 124 , line = ['Drama Thriller']
IDX = 125 , line = ['Drama Action Comedy Crime']
IDX = 126 , line = ['Romance Drama Thriller Crime']
IDX = 127 , line = ['Horror Thriller Mystery']
IDX = 128 , line = ['History Drama']
IDX = 129 , line = ['Horror Thriller']
IDX = 130 , line = ['Drama Comedy Romance']
IDX = 131 , line = ['Drama']
IDX = 132 , line = ['Fantasy Drama Mystery']
IDX = 133 , line = ['Romance Drama Crime']
IDX = 134 , line = ['Action Adventure Comedy Crime Thriller']
IDX = 135 , line = ['Drama']
IDX = 136 , line = ['Drama Comedy Crime']
IDX = 137 , line = ['Drama Horror']
IDX = 138 , line = ['Comedy Family']
IDX = 139 , line = ['Drama Romance']
IDX = 140 , line = ['Adventure Action']
IDX = 141 , line = ['Horror Thriller']
IDX = 142 , line = ['Drama Romance Foreign']
IDX = 143 , line = ['Thriller Science_Fiction Action']
IDX = 144 , line = ['Comedy Crime Drama Thriller']
IDX = 145 , line = ['History Drama']
IDX = 146 , line = ['Drama']
IDX = 147 , line = ['Horror Thriller']
IDX = 148 , line = ['Drama Romance Comedy']
IDX = 149 , line = ['Drama']
IDX = 150 , line = ['Comedy Drama Thriller']
IDX = 151 , line = ['Romance Drama Mystery']
IDX = 152 , line = ['Thriller']
IDX = 153 , line = ['Science_Fiction Action Comedy Horror']
IDX = 154 , line = ['Comedy']
IDX = 155 , line = ['Crime Drama Mystery']
IDX = 156 , line = ['Comedy Drama Romance']
IDX = 157 , line = ['Adventure Animation Fantasy']
IDX = 158 , line = ['History Drama']
IDX = 159 , line = ['Mystery Drama Thriller Horror']
IDX = 160 , line = ['Romance Comedy']
IDX = 161 , line = ['Comedy Adventure Crime']
IDX = 162 , line = ['Comedy Mystery']
IDX = 163 , line = ['Comedy']
IDX = 164 , line = ['Drama']
IDX = 165 , line = ['Horror Documentary Mystery']
IDX = 166 , line = ['Comedy']
IDX = 167 , line = ['Comedy Romance']
IDX = 168 , line = ['Action Thriller']
IDX = 169 , line = ['Action Adventure History Romance Drama']
IDX = 170 , line = ['Comedy Fantasy Science_Fiction']
IDX = 171 , line = ['Adventure Action Science_Fiction']
IDX = 172 , line = ['Adventure Fantasy Action Thriller Science_Fiction']
IDX = 173 , line = ['Drama']
IDX = 174 , line = ['Mystery Thriller']
IDX = 175 , line = ['Action Adventure Drama Family']
IDX = 176 , line = ['Comedy Family Drama']
IDX = 177 , line = ['Drama Family Fantasy']
IDX = 178 , line = ['Comedy Romance']
IDX = 179 , line = ['Romance Crime Drama']
IDX = 180 , line = ['Crime Thriller']
IDX = 181 , line = ['Drama']
IDX = 182 , line = ['Drama Action Romance']
IDX = 183 , line = ['Comedy Drama Fantasy Romance']
IDX = 184 , line = ['Science_Fiction Thriller']
IDX = 185 , line = ['Drama']
IDX = 186 , line = ['Horror Thriller Mystery']
IDX = 187 , line = ['Romance Comedy Crime']
IDX = 188 , line = ['Comedy Romance']
IDX = 189 , line = ['Comedy Drama Romance']
IDX = 190 , line = ['Comedy Horror']
IDX = 191 , line = ['Crime Drama Thriller']
IDX = 192 , line = ['Drama Crime Thriller']
IDX = 193 , line = ['History Documentary']
IDX = 194 , line = ['Drama Comedy Romance']
IDX = 195 , line = ['Adventure Fantasy Action Comedy Thriller']
IDX = 196 , line = ['Adventure Drama Romance War']
IDX = 197 , line = ['Comedy']
IDX = 198 , line = ['Comedy Animation Family']
IDX = 199 , line = ['Drama Romance']
IDX = 200 , line = ['Crime Drama']
IDX = 201 , line = ['Animation Fantasy']
IDX = 202 , line = ['Horror Mystery Thriller']
IDX = 203 , line = ['Drama Thriller Action']
IDX = 204 , line = ['Fantasy Drama Thriller Mystery Romance']
IDX = 205 , line = ['Fantasy Action Adventure']
IDX = 206 , line = ['Adventure Drama Family']
IDX = 207 , line = ['Thriller Fantasy Action Comedy']
IDX = 208 , line = ['Action Adventure Crime Thriller']
IDX = 209 , line = ['Action Comedy Thriller']
IDX = 210 , line = ['Drama Romance Western']
IDX = 211 , line = ['Horror Thriller']
IDX = 212 , line = ['Horror Mystery Crime']
IDX = 213 , line = ['Comedy Drama Romance']
IDX = 214 , line = ['Comedy Crime']
IDX = 215 , line = ['Drama']
IDX = 216 , line = ['Comedy Drama Romance Science_Fiction']
IDX = 217 , line = ['Comedy Family']
IDX = 218 , line = ['Adventure Fantasy Action']
IDX = 219 , line = ['Drama Thriller']
IDX = 220 , line = ['Comedy Music']
IDX = 221 , line = ['Drama']
IDX = 222 , line = ['Comedy Music Family Fantasy Animation']
IDX = 223 , line = ['Drama Music']
IDX = 224 , line = ['Action Comedy']
IDX = 225 , line = ['Drama Comedy']
IDX = 226 , line = ['Comedy Fantasy Romance']
IDX = 227 , line = ['Drama']
IDX = 228 , line = ['Adventure Action Science_Fiction']
IDX = 229 , line = ['Action Science_Fiction']
IDX = 230 , line = ['Animation Action Comedy Family']
IDX = 231 , line = ['Comedy Romance']
IDX = 232 , line = ['Drama Romance']
IDX = 233 , line = ['Comedy Drama']
IDX = 234 , line = ['Action Crime Thriller']
IDX = 235 , line = ['Crime Drama']
IDX = 236 , line = ['Comedy Family']
IDX = 237 , line = ['Action Horror Science_Fiction']
IDX = 238 , line = ['Fantasy Horror Thriller']
IDX = 239 , line = ['Comedy Music Romance']
IDX = 240 , line = ['Drama Romance']
IDX = 241 , line = ['Crime Drama Thriller']
IDX = 242 , line = ['Animation Family']
IDX = 243 , line = ['Action Adventure Drama Family']
IDX = 244 , line = ['Drama']
IDX = 245 , line = ['Comedy Romance']
IDX = 246 , line = ['Adventure Action Science_Fiction']
IDX = 247 , line = ['Action Adventure Comedy Western']
IDX = 248 , line = ['Fantasy Drama']
IDX = 249 , line = ['Drama']
IDX = 250 , line = ['Thriller Science_Fiction Drama']
IDX = 251 , line = ['Action Comedy']
IDX = 252 , line = ['Family Comedy Action']
IDX = 253 , line = ['Comedy Drama Romance']
IDX = 254 , line = ['Comedy Romance Family']
IDX = 255 , line = ['Western']
IDX = 256 , line = ['Animation Family Music']
IDX = 257 , line = ['Action Fantasy Horror Mystery']
IDX = 258 , line = ['Crime History']
IDX = 259 , line = ['Action Comedy Crime Drama']
IDX = 260 , line = ['Drama Crime Thriller']
IDX = 261 , line = ['Comedy']
IDX = 262 , line = ['Comedy Horror']
IDX = 263 , line = ['Comedy']
IDX = 264 , line = ['Drama Western']
IDX = 265 , line = ['Drama Horror Mystery']
IDX = 266 , line = ['Horror']
IDX = 267 , line = ['Action Adventure Comedy Fantasy']
IDX = 268 , line = ['Comedy Family Romance']
IDX = 269 , line = ['Thriller Drama']
IDX = 270 , line = ['Comedy']
IDX = 271 , line = ['Drama Crime']
IDX = 272 , line = ['Comedy']
IDX = 273 , line = ['Action Drama Thriller Crime Mystery']
IDX = 274 , line = ['Action Science_Fiction']
IDX = 275 , line = ['Drama']
IDX = 276 , line = ['Adventure Drama Action Comedy Romance']
IDX = 277 , line = ['Adventure Drama Family']
IDX = 278 , line = ['Drama Comedy Music']
IDX = 279 , line = ['Mystery Science_Fiction Thriller']
IDX = 280 , line = ['Comedy Drama Family Romance']
IDX = 281 , line = ['Comedy Family']
IDX = 282 , line = ['Drama Mystery Thriller Fantasy']
IDX = 283 , line = ['Horror']
IDX = 284 , line = ['Thriller Drama Horror']
IDX = 285 , line = ['Action Comedy']
IDX = 286 , line = ['Action Crime Drama Thriller']
IDX = 287 , line = ['Thriller']
IDX = 288 , line = ['Comedy']
IDX = 289 , line = ['Drama Thriller Crime Romance']
IDX = 290 , line = ['Fantasy Adventure Animation Comedy Family']
IDX = 291 , line = ['Comedy']
IDX = 292 , line = ['Comedy Romance']
IDX = 293 , line = ['Action Comedy']
IDX = 294 , line = ['Action Animation Science_Fiction']
IDX = 295 , line = ['Action Thriller War']
IDX = 296 , line = ['Horror Mystery Thriller']
IDX = 297 , line = ['Drama History']
IDX = 298 , line = ['Comedy Drama Crime']
IDX = 299 , line = ['Comedy Drama']
IDX = 300 , line = ['Drama Thriller']
IDX = 301 , line = ['Drama War Mystery']
IDX = 302 , line = ['Comedy Family Fantasy']
IDX = 303 , line = ['Drama Romance']
IDX = 304 , line = ['Thriller Adventure Mystery Fantasy']
IDX = 305 , line = ['Fantasy']
IDX = 306 , line = ['Drama']
IDX = 307 , line = ['Action Horror Science_Fiction Thriller']
IDX = 308 , line = ['Horror Mystery Thriller']
IDX = 309 , line = ['Horror']
IDX = 310 , line = ['Comedy Drama']
IDX = 311 , line = ['Adventure Action Thriller Mystery']
IDX = 312 , line = ['Drama Comedy History Music']
IDX = 313 , line = ['Drama Music']
IDX = 314 , line = ['Drama']
IDX = 315 , line = ['Drama History']
IDX = 316 , line = ['Drama']
IDX = 317 , line = ['Drama Horror Thriller']
IDX = 318 , line = ['Drama Mystery Thriller']
IDX = 319 , line = ['Horror Drama']
IDX = 320 , line = ['Science_Fiction']
IDX = 321 , line = ['Drama Mystery Thriller']
IDX = 322 , line = ['Comedy Drama']
IDX = 323 , line = ['Drama History']
IDX = 324 , line = ['Action Adventure Thriller']
IDX = 325 , line = ['Comedy Romance']
IDX = 326 , line = ['Drama Action']
IDX = 327 , line = ['Thriller Mystery']
IDX = 328 , line = ['Action Fantasy']
IDX = 329 , line = ['Science_Fiction Action Thriller']
IDX = 330 , line = ['Drama Animation War']
IDX = 331 , line = ['Comedy Romance']
IDX = 332 , line = ['Comedy']
IDX = 333 , line = ['Comedy']
IDX = 334 , line = ['Horror']
IDX = 335 , line = ['Documentary']
IDX = 336 , line = ['Action Fantasy']
IDX = 337 , line = ['Drama']
IDX = 338 , line = ['Action Comedy Crime Romance']
IDX = 339 , line = ['Thriller Mystery']
IDX = 340 , line = ['Action Drama Thriller Crime']
IDX = 341 , line = ['Horror Thriller']
IDX = 342 , line = ['Drama']
IDX = 343 , line = ['Comedy']
IDX = 344 , line = ['Comedy']
IDX = 345 , line = ['Action Adventure Romance Western']
IDX = 346 , line = ['Comedy Thriller Action Drama']
IDX = 347 , line = ['Action Crime Comedy']
IDX = 348 , line = ['Drama']
IDX = 349 , line = ['Drama Romance']
IDX = 350 , line = ['Thriller Crime Drama']
IDX = 351 , line = ['Thriller Drama Science_Fiction']
IDX = 352 , line = ['Science_Fiction Fantasy Action Adventure']
IDX = 353 , line = ['Action Adventure Thriller']
IDX = 354 , line = ['Adventure Action Comedy Thriller Crime']
IDX = 355 , line = ['Action Drama History Thriller']
IDX = 356 , line = ['Action Adventure Crime Drama']
IDX = 357 , line = ['Drama Thriller Horror']
IDX = 358 , line = ['Thriller Crime Drama']
IDX = 359 , line = ['Adventure Science_Fiction']
IDX = 360 , line = ['Family Fantasy Comedy']
IDX = 361 , line = ['Action Thriller Crime Mystery']
IDX = 362 , line = ['Drama Romance']
IDX = 363 , line = ['Action Drama Western']
IDX = 364 , line = ['Action Adventure Comedy Science_Fiction Western']
IDX = 365 , line = ['Comedy']
IDX = 366 , line = ['Animation Comedy Family']
IDX = 367 , line = ['Comedy Adventure Romance']
IDX = 368 , line = ['Horror Thriller']
IDX = 369 , line = ['Comedy Family Romance']
IDX = 370 , line = ['Drama Thriller']
IDX = 371 , line = ['Drama Fantasy']
IDX = 372 , line = ['Fantasy Drama']
IDX = 373 , line = ['Action Adventure Science_Fiction']
IDX = 374 , line = ['Mystery Thriller Drama']
IDX = 375 , line = ['Action Crime Drama Thriller']
IDX = 376 , line = ['Adventure Action Comedy Thriller Crime']
IDX = 377 , line = ['Crime Drama Thriller']
IDX = 378 , line = ['Comedy Romance']
IDX = 379 , line = ['Science_Fiction']
IDX = 380 , line = ['Drama Family']
IDX = 381 , line = ['Science_Fiction Action']
IDX = 382 , line = ['Comedy Drama']
IDX = 383 , line = ['Adventure Family']
IDX = 384 , line = ['Adventure Action Comedy Western']
IDX = 385 , line = ['Drama Romance']
IDX = 386 , line = ['Crime Comedy']
IDX = 387 , line = ['Music Drama Crime Romance']
IDX = 388 , line = ['Drama']
IDX = 389 , line = ['Adventure Action Animation']
IDX = 390 , line = ['Drama Mystery']
IDX = 391 , line = ['Drama']
IDX = 392 , line = ['Comedy Drama']
IDX = 393 , line = ['Horror Thriller']
IDX = 394 , line = ['Drama Romance']
IDX = 395 , line = ['Drama History Romance']
IDX = 396 , line = ['Action Thriller Adventure Crime']
IDX = 397 , line = ['Comedy Family']
IDX = 398 , line = ['Adventure Drama Family']
IDX = 399 , line = ['Drama Science_Fiction']
IDX = 400 , line = ['Drama Romance']
IDX = 401 , line = ['Action Drama Thriller']
IDX = 402 , line = ['Family']
IDX = 403 , line = ['Comedy Romance']
IDX = 404 , line = ['Comedy']
IDX = 405 , line = ['Drama']
IDX = 406 , line = ['Horror Comedy']
IDX = 407 , line = ['Romance Drama']
IDX = 408 , line = ['Drama Action Crime']
IDX = 409 , line = ['Horror']
IDX = 410 , line = ['Adventure Drama Thriller']
IDX = 411 , line = ['Adventure Drama Action History War']
IDX = 412 , line = ['Action Drama Thriller War']
IDX = 413 , line = ['Action Thriller Science_Fiction']
IDX = 414 , line = ['Adventure Action Fantasy']
IDX = 415 , line = ['History Drama']
IDX = 416 , line = ['Drama History Romance']
IDX = 417 , line = ['Comedy']
IDX = 418 , line = ['Action History War']
IDX = 419 , line = ['Drama Romance']
IDX = 420 , line = ['Action Crime Drama Thriller']
IDX = 421 , line = ['Drama Romance']
IDX = 422 , line = ['Romance Drama History War Music']
IDX = 423 , line = ['Drama']
IDX = 424 , line = ['Thriller Action Romance Science_Fiction Adventure']
IDX = 425 , line = ['Horror Thriller']
IDX = 426 , line = ['Action Comedy Crime Romance']
IDX = 427 , line = ['Action Drama Thriller']
IDX = 428 , line = ['Horror Comedy Thriller']
IDX = 429 , line = ['Crime Comedy Action']
IDX = 430 , line = ['Science_Fiction Action Adventure Fantasy Comedy']
IDX = 431 , line = ['Action Thriller Adventure']
IDX = 432 , line = ['Drama Thriller Crime']
IDX = 433 , line = ['Action Horror Thriller']
IDX = 434 , line = ['Comedy']
IDX = 435 , line = ['Comedy Drama Music Romance']
IDX = 436 , line = ['Thriller Mystery Drama Horror']
IDX = 437 , line = ['Comedy Drama Romance']
IDX = 438 , line = ['Adventure Comedy']
IDX = 439 , line = ['Documentary']
IDX = 440 , line = ['Romance Fantasy Drama Comedy']
IDX = 441 , line = ['Action Thriller']
IDX = 442 , line = ['Action Thriller Science_Fiction Adventure']
IDX = 443 , line = ['Comedy Drama Romance']
IDX = 444 , line = ['Drama Thriller Crime']
IDX = 445 , line = ['Documentary']
IDX = 446 , line = ['Horror Thriller']
IDX = 447 , line = ['Drama']
IDX = 448 , line = ['Drama Horror Mystery Thriller']
IDX = 449 , line = ['Action Thriller Crime']
IDX = 450 , line = ['Action Comedy Thriller Romance']
IDX = 451 , line = ['Comedy']
IDX = 452 , line = ['Drama Romance']
IDX = 453 , line = ['Horror Mystery']
IDX = 454 , line = ['Drama']
IDX = 455 , line = ['Comedy Romance']
IDX = 456 , line = ['Drama']
IDX = 457 , line = ['Adventure Family Fantasy']
IDX = 458 , line = ['Comedy Drama Romance']
IDX = 459 , line = ['Documentary']
IDX = 460 , line = ['Drama Foreign Romance']
IDX = 461 , line = ['Crime Drama Thriller']
IDX = 462 , line = ['Comedy War']
IDX = 463 , line = ['Crime Drama']
IDX = 464 , line = ['Horror']
IDX = 465 , line = ['War Drama History Action']
IDX = 466 , line = ['Action Comedy Drama Family Thriller']
IDX = 467 , line = ['Comedy']
IDX = 468 , line = ['Action Science_Fiction Adventure']
IDX = 469 , line = ['Comedy Romance']

array([[1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0]],
      dtype=int8)

In [17]:
#Codons la hamming_Loss

def hamming_loss(y_true : np.ndarray , y_pred : np.ndarray):
    # 1. Trouver où les valeurs sont différentes (True si erreur, False si correct)
    erreurs = y_true != y_pred

    # 2. Calculer la moyenne de ces erreurs
    hamming_loss_numpy = np.mean(erreurs)

    return hamming_loss_numpy

In [18]:
X_train_encoded.shape

(3818, 18857)

In [ ]:
# ÉTAPE 3: Classification Multilabel
X_train_encoded = X_train_encoded
y_train_encoded = y_train_multilabel
print("ÉTAPE 3: Entraînement des classifieurs Multilabel (Un model pour chaque classe)")

idx_to_label = {
    idx: label
    for idx, label in enumerate(unique_genres)
}
#Nombre de classes a predire
TARGETS = len(unique_genres)

models  = []

for j in range(TARGETS):
    print(f"Entrainement Numero {j} --> Genre : {idx_to_label[j]}")

    y_label =y_train_encoded[:, j]   # colonne du genre j

    model = LogisticRegression()  # logistic regression 

    score = k_fold_cross_validation(model=model , X= X_train_encoded , y=y_label , metric=hamming_loss , stratified=True)
    
    models.append(model)
    print(f"Hamming Loss pour {idx_to_label[j]} = {hamming_loss(y_label , model.predict(X_train_encoded))} ")

ÉTAPE 3: Entraînement des classifieurs Multilabel (Un model pour chaque classe)
Entrainement Numero 0 --> Genre : Action
Hamming Loss pour Action = 0.2388685175484547
Entrainement Numero 1 --> Genre : TV