# [#]() | Comparative benchmark of Perceptron classes from 
### *[`ifri_mini_ml_lib.neural_networks.Perceptron`](https://github.com/IFRI-AI-Classes/ifri_mini_ml_lib/blob/%40L2-26/G6/ifri_mini_ml_lib/neural_networks/perceptron.py)* and 
### *[`sklearn.linear_model.Perceptron`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Perceptron.html#sklearn.linear_model.Perceptron)*


<div id="container" style="display: flex; gap: 7px; background: white;">
  <div id="perceptron_0" style="display: flex; flex-direction: column; max-width: 540px; border-right: 1px solid black; justify-content: center; align-items: center;">
    <img class="perceptron" src="../assets/imgs/perceptron/Perceptron.svg" height="100%">
  </div>
  <div id="libs_" style="display: flex; flex-direction: column; padding: 4px 7px; max-width: 178px; background: black; border: 1px solid white; justify-content: center; align-items: center;">
    <i style="background: white; width: fit-content; padding: 12px; margin: 0 0 7px;">
      <img class="lib" src="../assets/imgs/libs/logo_iai_classes-f9a507daeb71d1ea34ff1ce4522fe02f.png" height="170" width="170"></i>
    <i style="background: white; width: fit-content; padding: 12px; margin: 7px 0 0;">
      <img class="lib" src="../assets/imgs/libs/scikit-learn-logo-without-subtitle.svg" height="170" width="170"></i>
  </div>
  <div id="ichio_pro" style="display: flex;">
    <div id="perceptron_1" style="display: flex; max-height: 400px; padding: 4px 21px; justify-content: center; align-items: center;">
      <img src="../assets/imgs/perceptron/1_Rm1Cd2KDoi1ACE-5KFP_Iw.png" height="100%">
    </div>
    <div id="perceptron_xor" style="display: flex; max-height: 400px; padding: 4px 21px; justify-content: center; align-items: center;">
      <img src="../assets/imgs/perceptron/1_GRubAZEl0qmrD4u4mCC0Ng.png" height="100%">
    </div>
  </div>
</div>


## [⊿]() | Main content
- Information about the Perceptron: Definition, purpose, history, algorithm, importance, limitations, ...
- Implementations : 
  - Preparation of three different types of datasets to demonstrate characteristics of the `Perceptron` (purpose, appropriate datasets, limitations)
  - Sequencing of processes (`importing`, `splitting`, `instantiation`, `fitting`, `prediction`, then `evaluation`) with `ifri_mini_ml_lib` and `sklearn` on these three data
- Summary tables of performance (`evaluation metrics`, `fitting runtime`, `prediction runtime`)
- References

---


# [▢]() | The [`Perceptron`](https://en.wikipedia.org/wiki/Perceptron)

The perceptron is a [supervised learning]() algorithm for binary classifiers (i.e., separating two classes). It was invented in 1957 by [Frank Rosenblatt]() at the Cornell University Aeronautics Laboratory. It is a [formal neuron](https://en.wikipedia.org/wiki/Artificial_neuron) equipped with a learning rule that automatically determines [synaptic weights](https://fr.wikipedia.org/wiki/Neurone_formel#Formulation_math%C3%A9matique) to separate a supervised learning problem. If the problem is linearly separable, a theorem ensures that the perceptron rule allows finding a separation between the two classes.

## [▻]() | Definition

The perceptron is the simplest type of direct-action neural network ([***Feedforward** neural network*](https://en.wikipedia.org/wiki/Feedforward_neural_network)). In its initial version, the perceptron is single-layered and has only one output ([Boolean]()) to which all Boolean inputs are connected. More generally, the inputs can be real numbers, and it then [linear classifier](https://en.wikipedia.org/wiki/Linear_classifier) for real vector data.

## [▻]() $M_1^*$ | Perceptron &nbsp; [$"Activation$ $Function"$](https://en.wikipedia.org/wiki/Activation_function)

The outputs of the `Perceptron` result from the application of the [`Heaviside function`](https://en.wikipedia.org/wiki/Heaviside_step_function) (threshold function), the only activation function to train a `single-layer perceptron` $--$ unlike the `multi-layer perceptron` (**[`MLP`](https://en.wikipedia.org/wiki/Multilayer_perceptron)**) which offers several options (at least one for each layer).


<div style="background: white; padding: 15px 10px;">
  <img id="activ_func_" src="../assets/imgs/perceptron/1_hm-Whb2f2dgObJuEoCuCAQ.png" height="125">
</div>

where 
- $X = \{{x_1, x_2, ..., x_n}\}$ | $X \in \mathbb{R^{n\times p}}$ et $x_i \in \mathbb{R^p}$, is the set of input data (a vector of vectors, an n-dimensional array)
- $w = \{{w_1, w_2, ..., w_n}\}$ | $w \in \mathbb{R^n}$, each corresponding to an entry ($w_i \rightarrow x_i$ $\Longrightarrow$ $\hat{y} =\sum_{i=0}^{n}w_i \times x_i + b$) and indicating its importance
- $b \in \mathbb{R}$, is a constant term that allows the activation function to be shifted in order to control the triggering threshold
- $v = w \times X + b$, weighted sum of entries
- $\forall$ $v \in \mathbb{R}$, 
$$
\hat{y} = 
\begin{cases}
1,& if & v \ge 0\\
0,& if & v < 0
\end{cases}
$$

## [▻]() $M_2^*$ | Parameter update using the **Stochastic Gradient Descent [SGD]** method

The update of the `weights` and the `bias` is done according to the [Stochastic Gradient Algorithm](https://en.wikipedia.org/wiki/Stochastic_gradient_descent) (the standard method of [gradient descent](https://en.wikipedia.org/wiki/Gradient_descent)) 

$$
w = w - 𝜂 \bigtriangledown Q(w)
$$
where, $𝜂$ is the iteration step size (sometimes called the learning rate in machine learning).

More precisely, according to Rosenblatt's rule, we have :
$$
w = w + 𝜂(y_j - \hat{y_j})\times X_j
$$
$$
b = b + 𝜂(y_j - \hat{y_j})
$$
where 
- $y_j$ the target value
- $\hat{y_j}$ the prediction(s) for each observation
- $y_j - \hat{y_j}$, the error
- $j$ -> each observation

## [▻]() | Learning algorithm

There are several learning algorithms for a perceptron. One of the earliest is the `Rosenblatt` perceptron algorithm, invented in `1957`, which aims to find the parameters of a hyperplane that correctly separates the two data classes :


<div style="background: white; color: black; padding: 21px 7px 14px">
<pre>Input&nbsp;: a sample <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle {\mathcal {S}}=\{(X_{1},y_{1}),~\dots ~,(X_{n},y_{n})\}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mrow class="MJX-TeXAtom-ORD">
          <mrow class="MJX-TeXAtom-ORD">
            <mi class="MJX-tex-caligraphic" mathvariant="script">S</mi>
          </mrow>
        </mrow>
        <mo>=</mo>
        <mo fence="false" stretchy="false">{</mo>
        <mo stretchy="false">(</mo>
        <msub>
          <mi>X</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>1</mn>
          </mrow>
        </msub>
        <mo>,</mo>
        <msub>
          <mi>y</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>1</mn>
          </mrow>
        </msub>
        <mo stretchy="false">)</mo>
        <mo>,</mo>
        <mtext>&nbsp;</mtext>
        <mo>…<!-- … --></mo>
        <mtext>&nbsp;</mtext>
        <mo>,</mo>
        <mo stretchy="false">(</mo>
        <msub>
          <mi>X</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>n</mi>
          </mrow>
        </msub>
        <mo>,</mo>
        <msub>
          <mi>y</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>n</mi>
          </mrow>
        </msub>
        <mo stretchy="false">)</mo>
        <mo fence="false" stretchy="false">}</mo>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle {\mathcal {S}}=\{(X_{1},y_{1}),~\dots ~,(X_{n},y_{n})\}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/0849eab8aa12ef2c5bb9b8c1770c42390116bc40" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.838ex; width:30.001ex; height:2.843ex;" alt="{\displaystyle {\mathcal {S}}=\{(X_{1},y_{1}),~\dots ~,(X_{n},y_{n})\}}"></span> of labeled data
Output&nbsp;: the weight matrix <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle W}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>W</mi>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle W}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/54a9c4c547f4d6111f81946cad242b18298d70b7" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.338ex; width:2.435ex; height:2.176ex;" alt="{\displaystyle W}"></span> such that <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle \forall (X_{k},y_{k})\in S,\quad y_{k}(\langle W,X_{k}\rangle +b)&gt;0}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi mathvariant="normal">∀<!-- ∀ --></mi>
        <mo stretchy="false">(</mo>
        <msub>
          <mi>X</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>k</mi>
          </mrow>
        </msub>
        <mo>,</mo>
        <msub>
          <mi>y</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>k</mi>
          </mrow>
        </msub>
        <mo stretchy="false">)</mo>
        <mo>∈<!-- ∈ --></mo>
        <mi>S</mi>
        <mo>,</mo>
        <mspace width="1em"></mspace>
        <msub>
          <mi>y</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>k</mi>
          </mrow>
        </msub>
        <mo stretchy="false">(</mo>
        <mo fence="false" stretchy="false">⟨<!-- ⟨ --></mo>
        <mi>W</mi>
        <mo>,</mo>
        <msub>
          <mi>X</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>k</mi>
          </mrow>
        </msub>
        <mo fence="false" stretchy="false">⟩<!-- ⟩ --></mo>
        <mo>+</mo>
        <mi>b</mi>
        <mo stretchy="false">)</mo>
        <mo>&gt;</mo>
        <mn>0</mn>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle \forall (X_{k},y_{k})\in S,\quad y_{k}(\langle W,X_{k}\rangle +b)&gt;0}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/0c78a148fee6b48e51938a3e8d92903d6b5fa1e4" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.838ex; width:37.501ex; height:2.843ex;" alt="{\displaystyle \forall (X_{k},y_{k})\in S,\quad y_{k}(\langle W,X_{k}\rangle +b)&gt;0}"></span>
1 Initialize <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle W=0_{\mathbb {R} ^{d+1}}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>W</mi>
        <mo>=</mo>
        <msub>
          <mn>0</mn>
          <mrow class="MJX-TeXAtom-ORD">
            <msup>
              <mrow class="MJX-TeXAtom-ORD">
                <mi mathvariant="double-struck">R</mi>
              </mrow>
              <mrow class="MJX-TeXAtom-ORD">
                <mi>d</mi>
                <mo>+</mo>
                <mn>1</mn>
              </mrow>
            </msup>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle W=0_{\mathbb {R} ^{d+1}}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/4a6583558c38ed1dc480c14603e3818fc1879a3d" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -1.005ex; width:10.683ex; height:2.843ex;" alt="{\displaystyle W=0_{\mathbb {R} ^{d+1}}}"></span>
2 <b>Repeat</b>
3    <b>For</b> <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle i=1}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>i</mi>
        <mo>=</mo>
        <mn>1</mn>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle i=1}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/9fb857369fbc28dab4b5d76bb835e6f196b1d1cf" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.338ex; width:5.063ex; height:2.176ex;" alt="{\displaystyle i=1}"></span> <b>to</b> <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle n}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>n</mi>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle n}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/a601995d55609f2d9f5e233e36fbe9ea26011b3b" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.338ex; width:1.395ex; height:1.676ex;" alt="{\displaystyle n}"></span>
4        <b>If</b> <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle y_{i}\langle W,X_{i}\rangle \leq 0}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>y</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>i</mi>
          </mrow>
        </msub>
        <mo fence="false" stretchy="false">⟨<!-- ⟨ --></mo>
        <mi>W</mi>
        <mo>,</mo>
        <msub>
          <mi>X</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>i</mi>
          </mrow>
        </msub>
        <mo fence="false" stretchy="false">⟩<!-- ⟩ --></mo>
        <mo>≤<!-- ≤ --></mo>
        <mn>0</mn>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle y_{i}\langle W,X_{i}\rangle \leq 0}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/dd78cae93ff799d0952c09a4a798226657b43e5e" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.838ex; width:14.202ex; height:2.843ex;" alt="{\displaystyle y_{i}\langle W,X_{i}\rangle \leq 0}"></span> <b>then</b>
5            <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle W\leftarrow W+y_{i}X_{i}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>W</mi>
        <mo stretchy="false">←<!-- ← --></mo>
        <mi>W</mi>
        <mo>+</mo>
        <msub>
          <mi>y</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>i</mi>
          </mrow>
        </msub>
        <msub>
          <mi>X</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>i</mi>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle W\leftarrow W+y_{i}X_{i}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/a96ad493833279bad240e817f8a757753ef2f59e" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.671ex; width:15.988ex; height:2.509ex;" alt="{\displaystyle W\leftarrow W+y_{i}X_{i}}"></span>
6    <b>End for</b>
7 <b>until there are no more errors</b>
8 <b>Return</b> <span class="mwe-math-element mwe-math-element-inline"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle W}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>W</mi>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle W}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/54a9c4c547f4d6111f81946cad242b18298d70b7" class="mwe-math-fallback-image-inline mw-invert skin-invert" aria-hidden="true" style="vertical-align: -0.338ex; width:2.435ex; height:2.176ex;" alt="{\displaystyle W}"></span>
</pre>
</div>

***Training steps*** : the one used (several exist depending on the needs and complexity)*

> [BEGINNING]()
>
>1. Random initialization of weights and bias
>> $"loop"$ : 
> > {
> - For each observation $X_{j_{j \in \{{1,...,p}\}}}$ in $x_{i_{i \in \{{1,...,n}\}}}$, we have : 
>   $X_j = \{{x_{1j}, x_{2j}, ..., x_{nj}}\}$
> 2. Calculation of the weighted sum of the inputs (often denoted $z$) : 
>   $z = w \times X_j + b$
> 3. Application of the activation function (functions in [$M_1^*$]()) : 
>   $\hat{y} = 1$ si $z \ge 0$, $0$ sinon
> 4. Update of weights and bias (functions in [$M_2^*$]())
> > }
>
> [END]()

## [▻]() | Introductory summary

The [`perceptron`]() is a binary linear classifier. Its limitations (non-linearity, single layer, lack of regression) are not implementation errors but theoretical constraints. It remains useful as a basic model and as an introduction to neural networks. To overcome these limitations, [`MLPs`]() with multiple layers and differentiable activation functions are used.

**[NOTE]()** : Comparisons are made based on 
- the evaluation metrics (*`accuracy`*, *`precision`*, *`rappel`*, *`f1-score`*) of the linear model,
- and the execution time of each function (``.fit(...)`` and ``.predict(...)``)

#
---


# [⌨️]() | Implementation

## [✓]()

In [1]:
# globals imports
#import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import time

In [2]:
import sys
PJ_PATH = r"C:\Users\HP\Downloads\_V_Schkodae_\_DEV_\_WORKSPACES_\_AI_\ifri_mini_ml_lib\ifri_mini_ml_lib--L2-26-G6"
if PJ_PATH not in sys.path: sys.path.append(PJ_PATH)

In [3]:
LIBS = ["ifri_mini_ml_lib", "sklearn"]
#T0 = time.time(); T = time.time() - T0; # print(f"Execution time \nT = {T}"); # PS = ["Training Time", "Prediction Time"]

## [⊌]() | Preparation of test data

Below are examples of data used for `binary classification`. This data will serve, on the one hand, to show the limits of the `perceptron`.

### [$A$](). Importing the `iris` dataset already present in sklearn
<!--[**INFO**]() :-->
- Included classes :
```py
    {0: "Setosa", 1: "Versicolor", 2: "Virginica"}
```
- Data adaptation (method : Use two classes, purpose : See if flowers are 'Setosa' or 'Versicolor')

In [4]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

In [5]:
X_IRIS = X[y != 2]; X_IRIS[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
y_iris = y[y != 2]; print( np.unique(y_iris, return_counts=True) )

(array([0, 1]), array([50, 50]))

### [$B$](). Using `make_classification` (or `make_blobs`) from sklearn
- Generating multiple points randomly by varying parameters

In [7]:
from sklearn.datasets import make_classification

#### [$B_0$](). - Creating linearly separable data to verify convergence

In [8]:
X_MCLASS, y_mclass = make_classification(
    n_samples=400,
    n_features=4,
    n_redundant=0,
    n_clusters_per_class=1,
    random_state=42
)

In [9]:
X_MCLASS[:5]

array([[ 1.78229859,  0.46250451,  0.46642998, -0.03564148],
       [ 0.99965997, -2.98354011, -0.08973569,  1.44011722],
       [ 0.72141075,  0.99082014,  1.22766899, -1.20964102],
       [ 0.55038317,  0.38880591, -0.24123606,  0.3520554 ],
       [ 0.70402732,  2.00302813, -0.02502696,  0.8177663 ]])

In [10]:
print( np.unique(y_mclass, return_counts=True) )

(array([0, 1]), array([202, 198]))

#### [$B_1$](). - Creating a non-separable dataset while controlling for noise and other factors (not used here)

In [11]:
X_NCLASS, y_nclass = make_classification(
    n_samples=400,
    n_features=4,
    class_sep=0.5,
    flip_y=0.2,
    random_state=42
)

In [12]:
X_NCLASS[:5]

array([[-0.52830288, -0.34759849, -0.81579191,  0.31348037],
       [-0.81053218,  0.94820684,  0.6675475 ,  0.92566531],
       [-0.59948438, -0.69280248, -1.31222037,  0.26615254],
       [-0.73292372,  0.24864243, -0.18498248,  0.65429058],
       [ 1.36420241, -0.64138689,  0.11296994, -1.27144908]])

In [13]:
print( np.unique(y_nclass, return_counts=True) )

(array([0, 1]), array([204, 196]))

### [$C$](). Non-linear dataset (representatives of logic gates)
- `AND` and `OR`
- `XOR` (model limit)

In [14]:
# EXAMPLES WITH SOME LOGIC GATES [INPUT]
# DATA - `BINARY CLASS_`|
#         x1  x2        |
X_BIN = [ [0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
X_BIN_V = np.where(np.array(X_BIN)==0, 1, 0)

Y_AND = [0, 0, 0, 1]  # y
Y_OR =  [0, 1, 1, 1]  # y
Y_XOR = [0, 1, 1, 0]  # y

In [15]:
# AUTO SPLITTING DATA
X_BIN_test, X_BIN_V_test = np.array(X_BIN), np.array(X_BIN_V)
y_and_test, y_or_test, y_xor_test = np.array(Y_AND), np.array(Y_OR), np.array(Y_XOR)

***[`XOR` function]()*** : &nbsp; <img id="xor_func" src="../assets/imgs/perceptron/1_B7j9TH-cCOEpYJzBT5T5zw.png" height="18px" style="background: #ffff; padding: 12px;">

##
```py
"""
>>> Chaining of processes (`imports`, `splitting`, `instantiation`, `fitting`, `prediction`, then, `evaluation`)
"""
```

In [16]:
PS = ["Training Time", "Prediction Time"] # LIBS = ["ifri_mini_ml_lib", "sklearn"]

Runtime_A, Runtime_B, Runtime_C = ( pd.DataFrame({}, index=PS, columns=LIBS) for _ in range(3) )

## [⇲]() | Class `ifri_mini_ml_lib.neural_networks.Perceptron`

In [17]:
from ifri_mini_ml_lib.neural_networks import Perceptron as PerceptronIMML

from ifri_mini_ml_lib.preprocessing.preparation import DataSplitter
splitter = DataSplitter(seed=42)

from ifri_mini_ml_lib.metrics.classification import accuracy, precision, recall, f1_score, confusion_matrix

In [18]:
# debug [split]
from sklearn.model_selection import train_test_split

In [19]:
def evalIMMLmetrics(y_true:np.ndarray, y_pred:np.ndarray):
  return {
    "Accuracy": accuracy(y_true, y_pred),
    "Precision": precision(y_true, y_pred),
    "Recall": recall(y_true, y_pred),
    "F1-score": f1_score(y_true, y_pred),
  }

### [$A$](). Using `IRIS` dataset

In [20]:
# Splitting data into training and testing sets
X_IRIS_train, X_IRIS_test, y_iris_train, y_iris_test = train_test_split(X_IRIS, y_iris, test_size=0.3)
#X_IRIS_train, X_IRIS_test, y_iris_train, y_iris_test = splitter.train_test_split(pd.DataFrame(X_IRIS), pd.DataFrame(y_iris), test_size=0.3)

pctIMML_iris = PerceptronIMML(early_stopping=False, patience=5)

In [21]:
T0 = time.time()
pctIMML_iris.fit(X=X_IRIS_train, y=y_iris_train)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_A.loc[PS[0], LIBS[0]] = T

Execution time : 0.11791491508483887

In [22]:
T0 = time.time()
y_iris_pred = pctIMML_iris.predict(X=X_IRIS_test)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_A.loc[PS[1], LIBS[0]] = T

y_iris_pred

Execution time : 0.0

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1])

[`EVAL`]() | `pctIMML_iris`

In [23]:
SCORE_A = pctIMML_iris.score(X=X_IRIS_test, y=y_iris_test)
SCORE_A

np.float64(1.0)

In [24]:
CONF_MTX_A = confusion_matrix(y_true=y_iris_test, y_pred=y_iris_pred)
CONF_MTX_A

{np.int64(0): {np.int64(0): 17, np.int64(1): 0},
 np.int64(1): {np.int64(0): 0, np.int64(1): 13}}

In [25]:
METRICS_A = evalIMMLmetrics(y_true=y_iris_test, y_pred=y_iris_pred)
METRICS_A

{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1-score': 1.0}

### [$B$](). Using `make_classification` generated dataset

In [26]:
# Splitting data into training and testing sets
X_MCLASS_train, X_MCLASS_test, y_mclass_train, y_mclass_test = train_test_split(X_MCLASS, y_mclass, test_size=0.3, random_state=42)

pctIMML_mclass = PerceptronIMML(early_stopping=False, patience=5)

In [27]:
T0 = time.time()
pctIMML_mclass.fit(X=X_MCLASS_train, y=y_mclass_train)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_B.loc[PS[0], LIBS[0]] = T

Execution time : 0.1591947078704834

In [28]:
T0 = time.time()
y_mclass_pred = pctIMML_mclass.predict(X=X_MCLASS_test)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_B.loc[PS[1], LIBS[0]] = T

y_mclass_pred

Execution time : 0.0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

[`EVAL`]() | `pctIMML_mclass`

In [29]:
SCORE_B = pctIMML_mclass.score(X=X_MCLASS_test, y=y_mclass_test)
SCORE_B

np.float64(0.6583333333333333)

In [30]:
CONF_MTX_B = confusion_matrix(y_true=y_mclass_test, y_pred=y_mclass_pred)
CONF_MTX_B

{np.int64(0): {np.int64(0): 58, np.int64(1): 2},
 np.int64(1): {np.int64(0): 39, np.int64(1): 21}}

In [31]:
METRICS_B = evalIMMLmetrics(y_true=y_mclass_test, y_pred=y_mclass_pred)
METRICS_B

{'Accuracy': 0.6583333333333333,
 'Precision': 0.9130434782608695,
 'Recall': 0.35,
 'F1-score': 0.5060240963855421}

### [$C$](). Using **binary** dataset (non-linear) with `AND`, `OR`, `XOR` functions

In [32]:
pctIMML_bin = PerceptronIMML(early_stopping=False) # logic functions model

In [33]:
# AND function
pctIMML_bin.fit(X=X_BIN_test, y=y_and_test)
# ----------------------------------------------
y_and_pred = pctIMML_bin.predict(X=X_BIN_V_test)
y_and_pred

array([1, 0, 0, 0])

In [34]:
# OR function
pctIMML_bin.fit(X=X_BIN_test, y=y_or_test)
# ----------------------------------------------
y_or_pred = pctIMML_bin.predict(X=X_BIN_V_test)
y_or_pred

array([1, 1, 1, 0])

In [35]:
# XOR function (with x_bin inversed) | id=0
pctIMML_bin.fit(X=X_BIN_test, y=y_xor_test)
# ----------------------------------------------
y_xor_v_pred = pctIMML_bin.predict(X=X_BIN_V_test)
y_xor_v_pred

array([0, 0, 0, 0])

In [36]:
# XOR function | id=1
T0 = time.time()
pctIMML_bin.fit(X=X_BIN_test, y=y_xor_test)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_C.loc[PS[0], LIBS[0]] = T

Execution time : 0.12733817100524902

In [37]:
T0 = time.time()
y_xor_pred = pctIMML_bin.predict(X=X_BIN_test)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_C.loc[PS[1], LIBS[0]] = T

y_xor_pred

Execution time : 0.0

array([0, 0, 0, 0])

[`EVAL`]() | `pctIMML_bin`::xor[1] // _function

In [38]:
SCORE_C = pctIMML_bin.score(X=X_BIN_test, y=y_xor_test)
SCORE_C

np.float64(0.5)

In [39]:
CONF_MTX_C = confusion_matrix(y_true=y_xor_test, y_pred=y_xor_pred)
CONF_MTX_C

{np.int64(0): {np.int64(0): 2, np.int64(1): 0},
 np.int64(1): {np.int64(0): 2, np.int64(1): 0}}

In [40]:
METRICS_C = evalIMMLmetrics(y_true=y_xor_test, y_pred=y_xor_pred)
METRICS_C

{'Accuracy': 0.5, 'Precision': 0, 'Recall': 0.0, 'F1-score': 0}

```py
"""
NOTE: The model cannot accurately predict XOR function output
```

## [⇲]() | Class `sklearn.linear_model.Perceptron`

In [41]:
from sklearn.linear_model import Perceptron as PerceptronSKL

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [42]:
def evalSKLmetrics(y_true:np.ndarray, y_pred:np.ndarray):
  return {
    "Accuracy": accuracy_score(y_true, y_pred),
    "Precision": precision_score(y_true, y_pred),
    "Recall": recall_score(y_true, y_pred),
    "F1-score": f1_score(y_true, y_pred),
  }

### [$A$](). Using `IRIS` dataset

In [43]:
# Splitting data into training and testing sets
X_IRIS_train_, X_IRIS_test_, y_iris_train_, y_iris_test_ = train_test_split(X_IRIS, y_iris, test_size=0.3, random_state=42)

pctSKL_iris = PerceptronSKL(n_iter_no_change=5)

In [44]:
T0 = time.time()
pctSKL_iris.fit(X=X_IRIS_train_, y=y_iris_train_)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_A.loc[PS[0], LIBS[1]] = T

Execution time : 0.0059473514556884766

In [45]:
T0 = time.time()
y_iris_pred_ = pctSKL_iris.predict(X=X_IRIS_test_)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_A.loc[PS[1], LIBS[1]] = T

y_iris_pred_

Execution time : 0.0

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1])

[`EVAL`]() | `pctSKL_iris`

In [46]:
CONF_MTX_A_ = confusion_matrix(y_true=y_iris_test_, y_pred=y_iris_pred_)
CONF_MTX_A_

array([[17,  0],
       [ 0, 13]])

In [47]:
METRICS_A_ = evalSKLmetrics(y_true=y_iris_test_, y_pred=y_iris_pred_)
METRICS_A_

{'Accuracy': 1.0, 'Precision': 1.0, 'Recall': 1.0, 'F1-score': 1.0}

### [$B$](). Using `make_classification` generated dataset

In [48]:
# Splitting data into training and testing sets
X_MCLASS_train_, X_MCLASS_test_, y_mclass_train_, y_mclass_test_ = train_test_split(X_MCLASS, y_mclass, test_size=0.3, random_state=42)

pctSKL_mclass = PerceptronSKL(n_iter_no_change=5)

In [49]:
T0 = time.time()
pctSKL_mclass.fit(X=X_MCLASS_train_, y=y_mclass_train_)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_B.loc[PS[0], LIBS[1]] = T

Execution time : 0.006693601608276367

In [50]:
T0 = time.time()
y_mclass_pred_ = pctSKL_mclass.predict(X=X_MCLASS_test_)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_B.loc[PS[1], LIBS[1]] = T

y_mclass_pred

Execution time : 0.0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

[`EVAL`]() | `pctSKL_mclass`

In [51]:
CONF_MTX_B_ = confusion_matrix(y_true=y_mclass_test_, y_pred=y_mclass_pred_)
CONF_MTX_B_

array([[52,  8],
       [16, 44]])

In [52]:
METRICS_B_ = evalSKLmetrics(y_true=y_mclass_test_, y_pred=y_mclass_pred_)
METRICS_B_

{'Accuracy': 0.8,
 'Precision': 0.8461538461538461,
 'Recall': 0.7333333333333333,
 'F1-score': 0.7857142857142857}

### [$C$](). Using **binary** dataset (non-linear) with `AND`, `OR`, `XOR` functions

In [53]:
pctSKL_bin = PerceptronSKL() # logic functions model

In [54]:
# AND function
pctSKL_bin.fit(X=X_BIN_test, y=y_and_test)
# ----------------------------------------------
y_and_pred_ = pctSKL_bin.predict(X=X_BIN_V_test)
y_and_pred_

array([1, 0, 0, 0])

In [55]:
# OR function
pctSKL_bin.fit(X=X_BIN_test, y=y_or_test)
# ----------------------------------------------
y_or_pred_ = pctSKL_bin.predict(X=X_BIN_V_test)
y_or_pred_

array([1, 1, 1, 0])

In [56]:
# XOR function (with x_bin inversed) | id=0
pctSKL_bin.fit(X=X_BIN_test, y=y_xor_test)
# ----------------------------------------------
y_xor_v_pred_ = pctSKL_bin.predict(X=X_BIN_V_test)
y_xor_v_pred_

array([0, 0, 0, 0])

In [57]:
# XOR function | id=1
T0 = time.time()
pctSKL_bin.fit(X=X_BIN_test, y=y_xor_test)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_C.loc[PS[0], LIBS[1]] = T

Execution time : 0.004527568817138672

In [58]:
T0 = time.time()
y_xor_pred_ = pctSKL_bin.predict(X=X_BIN_test)

T = time.time() - T0
print(f"Execution time : {T}")
Runtime_C.loc[PS[1], LIBS[1]] = T

y_xor_pred_

Execution time : 0.0022895336151123047

array([0, 0, 0, 0])

[`EVAL`]() | `pctSKL_bin`::xor[1] // _function

In [59]:
CONF_MTX_C_ = confusion_matrix(y_true=y_xor_test, y_pred=y_xor_pred_)
CONF_MTX_C_

array([[2, 0],
       [2, 0]])

In [60]:
METRICS_C_ = evalSKLmetrics(y_true=y_xor_test, y_pred=y_xor_pred_)
METRICS_C_

c:\Users\HP\.user_AILenv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

{'Accuracy': 0.5, 'Precision': 0.0, 'Recall': 0.0, 'F1-score': 0.0}

```py
"""
NOTE: The model cannot accurately predict XOR function output
```

---

#
---
## [▦]() | Summary tables

[`Metrics`]()::`eval()` and [`RunTime`]()::`eval()`

### [$A$](). `IRIS`

In [61]:
CORE_A = pd.DataFrame(
  data=[METRICS_A, METRICS_A_],
).transpose()
CORE_A.columns = LIBS

CORE_A = pd.concat([CORE_A, Runtime_A])
CORE_A.T

,Accuracy,Precision,Recall,F1-score,Training Time,Prediction Time
ifri_mini_ml_lib,1.0,1.0,1.0,1.0,0.117915,0.0
sklearn,1.0,1.0,1.0,1.0,0.005947,0.0

### [$B$](). `make_classification`

In [62]:
CORE_B = pd.DataFrame(
  data=[METRICS_B, METRICS_B_]
).transpose()
CORE_B.columns = LIBS

CORE_B = pd.concat([CORE_B, Runtime_B])
CORE_B.T

,Accuracy,Precision,Recall,F1-score,Training Time,Prediction Time
ifri_mini_ml_lib,0.658333,0.913043,0.35,0.506024,0.159195,0.0
sklearn,0.8,0.846154,0.733333,0.785714,0.006694,0.0

### [$C$](). `XOR` function

In [63]:
CORE_C = pd.DataFrame(
  data=[METRICS_C, METRICS_C_]
).transpose()
CORE_C.columns = LIBS

CORE_C = pd.concat([CORE_C, Runtime_C])
CORE_C.T

,Accuracy,Precision,Recall,F1-score,Training Time,Prediction Time
ifri_mini_ml_lib,0.5,0.0,0.0,0.0,0.127338,0.0
sklearn,0.5,0.0,0.0,0.0,0.004528,0.00229

```py
"""
NOTE : The model cannot accurately predict XOR function output
```

---

In [64]:
PJ_PATH = r"C:\Users\HP\Downloads\_V_Schkodae_\_DEV_\_WORKSPACES_\_AI_\ifri_mini_ml_lib\ifri_mini_ml_lib--L2-26-G6"
if PJ_PATH in sys.path: sys.path.remove(PJ_PATH)
# sys.path

---
# [⊷]() | `References`


- [Perceptron — scikit-learn 1.8.0 documentation]() ⊷ https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Perceptron.html#sklearn.linear_model.Perceptron
- [Perceptron — Wikipédia]() ⊷ https://en.wikipedia.org/wiki/Perceptron
- [Activation function - Wikipedia]() ⊷ https://en.wikipedia.org/wiki/Activation_function
- [Heaviside step function - Wikipedia]() ⊷ https://en.wikipedia.org/wiki/Heaviside_step_function
- [Deep Learning : Perceptrons simples et multicouches]() ⊷ https://eric.univ-lyon2.fr/ricco/cours/slides/reseaux_neurones_perceptron.pdf
- [Perceptrons, fonctions logiques et problème XOR]() ⊷ https://ichi.pro/fr/perceptrons-fonctions-logiques-et-probleme-xor-61342067554570
- [Multilayer perceptron - Wikipedia]() ⊷ https://en.wikipedia.org/wiki/Multilayer_perceptron

__________________________________________[END]() &nbsp; benchmark__________________________________________
_____________________